"use client";
import { useEffect, useRef, useState, useId } from 'react';
import { Crown, Smile, Check, X, Heart, Sparkles, Flower2, Wine } from 'lucide-react';
function Star({className=''}:{className?:string}){return <span className={`star ${className}`} aria-hidden="true">✦</span>}
function Logo({monogram=false}:{monogram?:boolean}){
 const clip=useId();const x=monogram?1060:90;const y=monogram?255:195;const width=monogram?460:955;const height=monogram?575:720;
 return <svg className={monogram?'identity monogram':'identity wordmark'} viewBox={`${x} ${y} ${width} ${height}`} style={{overflow:'hidden'}} aria-hidden="true"><defs><clipPath id={clip} clipPathUnits="userSpaceOnUse"><rect x={x} y={y} width={width} height={height}/></clipPath></defs><g clipPath={`url(#${clip})`}><image href="/assets/identity-clean.webp" width="1536" height="1024"/></g></svg>
}
function Bow({className=''}:{className?:string}){return <img className={`ribbon ${className}`} src="/assets/satin-bow.webp" alt="" aria-hidden="true"/>}
export default function Home(){
 const [phase,setPhase]=useState<'sealed'|'opening'|'opened'>('sealed');
 const [transition,setTransition]=useState<'entering'|'leaving'|null>(null);const transitionTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [panel,setPanel]=useState<'details'|'form'|'success'>('details');
 const [cardFront,setCardFront]=useState<'photo'|'info'>('info');
 const bringCardToFront=(card:'photo'|'info')=>setCardFront(card);
 const [guests,setGuests]=useState<string[]>(['']);const [guestStep,setGuestStep]=useState<'count'|'names'>('count');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const root=useRef<HTMLElement>(null);const title=useRef<HTMLHeadingElement>(null);const request=useRef('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(transitionTimer.current)clearTimeout(transitionTimer.current)},[]);
 useEffect(()=>{const el=root.current;if(!el)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0,x=0,y=0,tx=0,ty=0;
 function update(){frame=0;x+=(tx-x)*.08;y+=(ty-y)*.08;el!.style.setProperty('--mx',x.toFixed(3));el!.style.setProperty('--my',y.toFixed(3));if(Math.abs(tx-x)+Math.abs(ty-y)>.002)frame=requestAnimationFrame(update)}
 function move(e:PointerEvent){if(reduced.matches||e.pointerType!=='mouse')return;const b=el!.getBoundingClientRect();tx=(e.clientX-b.left)/b.width*2-1;ty=(e.clientY-b.top)/b.height*2-1;if(!frame)frame=requestAnimationFrame(update)}
 function leave(){tx=ty=0;if(!frame)frame=requestAnimationFrame(update)}
 el.addEventListener('pointermove',move,{passive:true});el.addEventListener('pointerleave',leave);return()=>{cancelAnimationFrame(frame);el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave)}},[]);
 function openEnvelope(){if(phase!=='sealed')return;setPhase('opening');timer.current=setTimeout(()=>{setPhase('opened');requestAnimationFrame(()=>title.current?.focus({preventScroll:true}))},window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:2300)}
 function attend(){if(transition)return;request.current=crypto.randomUUID();setError('');setGuestStep('count');if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setPanel('form');return}setTransition('entering');transitionTimer.current=setTimeout(()=>{setPanel('form');transitionTimer.current=setTimeout(()=>setTransition(null),450)},550)}
 function returnToInvite(){if(transition)return;(document.activeElement as HTMLElement)?.blur();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setPanel('details');return}setTransition('leaving');transitionTimer.current=setTimeout(()=>{setPanel('details');window.scrollTo({top:0,left:0,behavior:'instant'});requestAnimationFrame(()=>title.current?.focus({preventScroll:true}));transitionTimer.current=setTimeout(()=>setTransition(null),550)},350)}
 async function submit(e:React.FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const r=await fetch('/api/presenca',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({names:guests,count:guests.length,requestId:request.current})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Não foi possível confirmar. Tente novamente.');setPanel('success')}catch(e){setError(e instanceof Error?e.message:'Tente novamente.')}finally{setSaving(false)}}
 function resizeParty(count:number){setGuests(previous=>Array.from({length:count},(_,index)=>previous[index]||''));setError('')}
 useEffect(()=>{if(phase!=='opened'||panel!=='details'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const paths=root.current?.querySelectorAll<SVGGeometryElement>('.ambient-doodles svg path,.ambient-doodles svg circle,.doodle-play svg path,.doodle-play svg line,.doodle-play svg circle,.crown path,.heart-doodle path');const animations:Animation[]=[];paths?.forEach((path,index)=>{path.setAttribute('pathLength','1');path.style.strokeDasharray='1';path.style.strokeDashoffset='0';animations.push(path.animate([{strokeDashoffset:'1',opacity:0},{strokeDashoffset:'.9',opacity:1,offset:.12},{strokeDashoffset:'0',opacity:1,offset:.28},{strokeDashoffset:'0',opacity:1,offset:.92},{strokeDashoffset:'1',opacity:0}],{duration:6000,delay:350+index*100,iterations:Infinity,easing:'ease-in-out'}))});return()=>animations.forEach(animation=>animation.cancel())},[phase,panel]);

 useEffect(()=>{if(panel==='form'&&!transition)root.current?.querySelector<HTMLElement>('.rsvp-page [data-focus-target]')?.focus({preventScroll:true})},[panel,guestStep,transition]);
 function renderPanel(view:typeof panel){return <div className={`content-panel panel-${view}`} key={view}>
 {view==='details'?<><p className="invite-line">Vem comemorar comigo</p><div className="postcard-layout"><div className="date-column"><div className="event-date"><strong>19.12</strong><span>DEZEMBRO</span></div><div className="event-time"><span>A PARTIR DAS</span><strong>14h</strong></div><p className="location">Local a definir</p></div><div className="message-column"><p className="barbecue">Churras liberado,<br/>mas traga sua bebida. <Smile aria-hidden="true" strokeWidth={1.3}/></p><button className="rsvp" onClick={attend}>Marcar presença<Star/></button><p className="closing">Vai ser incrível<br/>ter você lá!</p></div></div></>:view==='form'?<><button className="back" onClick={returnToInvite} aria-label="Voltar aos detalhes" disabled={saving}><X size={18}/></button><p className="panel-kicker">19 de dezembro · 14h</p><h2>{guestStep==='count'?'Quantas pessoas vão?':'Quem vai com você?'}</h2>{guestStep==='count'?<div className="party-count"><label htmlFor="party-size">Conte você e seus acompanhantes</label><select data-focus-target id="party-size" value={guests.length} onChange={e=>resizeParty(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>{i+1} {i===0?'pessoa':'pessoas'}</option>)}</select><button className="rsvp" onClick={()=>setGuestStep('names')}>Continuar<Star/></button></div>:<form onSubmit={submit}><div className="guest-heading"><span>{guests.length} {guests.length===1?'pessoa':'pessoas'}</span><button type="button" onClick={()=>setGuestStep('count')} disabled={saving}>Alterar quantidade</button></div><div className="guest-fields">{guests.map((guest,index)=><div className="guest-field" key={index}><label htmlFor={`guest-${index}`}>{index===0?'Seu nome':`Acompanhante ${index}`}</label><input data-focus-target={index===0} id={`guest-${index}`} name={`guest-${index}`} autoComplete={index===0?'name':'off'} placeholder="Nome e sobrenome" required minLength={2} maxLength={80} value={guest} onChange={e=>setGuests(previous=>previous.map((value,i)=>i===index?e.target.value:value))} disabled={saving}/></div>)}</div><p className="form-error" role="alert">{error}</p><button className="rsvp" disabled={saving}>{saving?'Confirmando…':'Confirmar presença'}<Star/></button></form>}<p className="closing">Vamos celebrar juntos!</p></>:<div className="success" role="status"><div className="celebration" aria-hidden="true"><Star/><Star/><Star/><Star/><Star/></div><span className="success-symbol"><Check/></span><h2>Presença confirmada!</h2><p>{guests.length===1?`${guests[0].trim()}, sua presença está confirmada.`:`Confirmamos a presença de ${guests.length} pessoas.`}<br/><strong>19 de dezembro, às 14h.</strong></p><ul className="confirmed-guests">{guests.map((guest,index)=><li key={index}>{guest.trim()}</li>)}</ul><p className="closing">Vai ser incrível ter você lá!</p><button className="back-to-invite" onClick={returnToInvite}>Voltar ao convite</button></div>}
 </div>}

 return <main ref={root} className={`experience phase-${phase} screen-${panel} ${transition?`transition-${transition}`:""}`}>
 <div className="botanical-scene" aria-hidden="true"><div className="foliage foliage-left"/><div className="foliage foliage-right"/></div><div className="ambient" aria-hidden="true"><span className="script-initial one">B</span><span className="script-initial two">B</span><div className="ambient-doodles" aria-hidden="true"><Crown className="ornament-crown" strokeWidth={1}/><Heart className="ornament-heart" strokeWidth={1}/><Sparkles className="ornament-stars" strokeWidth={1}/><Flower2 className="ornament-flower" strokeWidth={1}/></div><Star className="ambient-one"/><Star className="ambient-two"/><span className="ambient-orbit"/></div>
 {phase!=='opened'&&<section className="sealed-scene" aria-label="Abrir convite"><p className="prelude">Um convite especial para você</p><button className="envelope-button" onClick={openEnvelope} disabled={phase==='opening'} aria-label="Clique para abrir o convite do Niver da Bê"><span className="envelope"><span className="envelope-back"/><span className="letter letter-photo"><img src="/assets/be-pose-v2.webp" alt=""/><Logo/></span><span className="letter letter-info"><span>Vem comemorar comigo</span><strong>19.12 · 14H</strong><span>Vai ser incrível ter você lá!</span></span><span className="envelope-front"/><span className="envelope-flap"/><span className="seal"><Logo monogram/></span><Bow className="envelope-ribbon"/></span></button><button className="open-hint" onClick={openEnvelope} disabled={phase==='opening'}>{phase==='opening'?'Seu convite está abrindo…':'Clique para abrir'}<Star/></button></section>}
 {phase==='opened'&&<article className="invitation" aria-label="Convite do aniversário da Bê"><section className={`portrait-scene card-photo ${cardFront==='photo'?'is-front':'is-back'}`} aria-label="Retrato da Bê" onMouseEnter={()=>bringCardToFront('photo')} onClick={()=>bringCardToFront('photo')}><div className="polaroid"><div className="photo-window"><img className="backdrop" src="/assets/rose-scene.webp" alt=""/><div className="photo-gold" aria-hidden="true"><span className="gold-orbit"/><span className="gold-orbit second"/><span className="gold-photo-word">B</span><span className="gold-speck first">✦</span><span className="gold-speck last">✧</span></div><img className="portrait" src="/assets/be-pose-v2.webp" alt="Bê, com cabelo escuro e mechas claras, de óculos e blusa vermelha" fetchPriority="high"/></div><header className="brand"><h1 ref={title} tabIndex={-1}><span className="sr-only">Niver da Bê</span><Logo/></h1></header><p className="photo-caption">É sobre celebrar tudo o que é bom.</p></div><Bow className="photo-ribbon"/></section><section className={`invitation-content card-info ${cardFront==='info'?'is-front':'is-back'}`} onMouseEnter={()=>bringCardToFront('info')} onClick={(e)=>{if((e.target as HTMLElement).closest('button,input,select,textarea'))return;bringCardToFront('info')}}><div className="doodle-play" aria-hidden="true"><Sparkles data-doodle className="content-doodle" aria-hidden="true" strokeWidth={1}/><Flower2 data-doodle className="flower-doodle" aria-hidden="true" strokeWidth={1}/><Wine data-doodle className="wine-doodle" aria-hidden="true" strokeWidth={1}/></div><Bow className="footer-ribbon"/>{renderPanel('details')}<footer className="signature"><span/>com carinho, Bê<span/></footer></section></article>}
 {panel!=='details'&&<section className="rsvp-page" aria-label="Confirmação de presença"><div className="doodle-play" aria-hidden="true"><Sparkles className="content-doodle"/><Flower2 className="flower-doodle"/><Wine className="wine-doodle"/></div>{renderPanel(panel)}<footer className="signature"><span/>com carinho, Bê<span/></footer><Bow className="footer-ribbon"/></section>}<div className="page-wash" aria-hidden="true"/></main>
}
